= AEE -- Bolivia

[qand]
lider o seguidor?::
ambos

[quote]
pesnsar, sentir y actuar

la asociacion de ingenieros de energia fue fundada por al thumann durante la crissi del petroleo de los años setenta con la mission de promover la conservaicion y la eficiencia engergetica. 
la aee es una asocacion de profesinales sin fines de lucro.

en la actualizdad, aee sirev a mas de 28k profesionales miembros, +32k profesionales certificados en termas de energia, +105 paises, 61 capitulos en usa, +45 capitulos internacionales, 27 capitulos estudiantes, y es una fuente principal de informacion en los campos dinamicoss de eficiencia enegertica, desregulacion de servicios publicos, gestion de instalaciones, ingenieria de plantas y cumplimineto ambiental.

con una gama completa de prgogramas de divulgacion de informacion a traves de sus seminarios tecnicos, conferenias y sus programas de certifiaccion reconodcidos internacinallmente, aee ofrece a sus mirmeos una variedad deherramietnas de recusrsos de informacion.

== presencia de la aee en latam

|===
|chapter |city |country

|
|===

=== bolivia chapter

villa luz #6, av. beni & sixth ring
santa cruz 123456
bolivia

phone: 70722333
contact: oscar siles chavez
email: oscar.siles.chavez@gmail.com