= Decision-Making Theory
:stem: latexmath

== Concepts

* A decision  is a selection between more than one alternative, which occurs in numerous and diverse situations in life.
* The theory of decisions provides a useful way to classify models for decision making.
* It will be assumed that the problem has been defined, that all the data is available and that the alternative courses of action have been identified.
The task is then to select the best alternative.
The theory of decisions says that this task of making a selection will fall into one of *four general categories* depending on the personal ability to predict the consequences of each alternative.

.General Categories of Decision
|===
| Category | Type of Predicted Consequence

| Under Certainty
| Deterministic Decision

| Under Risk
| Probabilistic Decision

| Under Uncertainty
| Unknown Decisions

| Under Conflict
| Decisions Influenced by an Opponent
|===

== Categories

=== Decision-Making Under Certainty
=== Decision-Making Under Risk

This category includes those decisions for which the consequences of a given action depend on some probabilistic event.

Example::
Suppose you have a small shop selling pine trees for Christmas.
The first task is to decide how many pines to order for the next season.
Suppose you have to pay $3.5 USD for each tree, and you can order only lots of 100 and plan to sell them for $8 USD each.
Of course, if they are not sold, they have no recovery value.
Sales records at churches are studied and the potential growth of sales with other vendors is analyzed, arriving at the following estimates for the coming season.

|===
| Pine Sales | Probability

| 100
| 30%

| 200
| 30%

| 300
| 40%
|===

==== Decision-Making Based on Mathematical Expectation

Taking the last example, the decision maker can use the concept of mathematical expectation to make the decision.

.Mathematical expectation formula
[stem]
++++
E(x) = \displaystyle\sum_{i=x_i}^{n}{x_i * p}
++++

.Where:
* stem:[E(x)] is the mathematical expectation.
* stem:[x_i] is the value of the variable (pine sales).
* stem:[n] is the number of possible values of the variable (how many pine sales).
* stem:[p] is the probability of occurrence of the variable.

Therefore the mathematical expectation is:

[stem]
++++
E(x) = \displaystyle\sum_{i=1}^{3}{[100, 200, 300] * [0.3, 0.3, 0.4]} == 210 \approx 200
++++

==== Decision-Making Based on Costs

|===
| | 100 | 200 | 300

|100
|450
|450
|450

|200
|100
|900
|900

|300
|-250
|550
|1350
|===

.Utility formula
[stem]
++++
\text{utility} = \{sales} - \text{costs}
++++

==== Decision-Making Based on Costs and Probability

|===
| | 100 | 200 | 300 | 
| | 0.3 | 0.3 | 0.4 | Profit Average
| 100 | 450 | 450 | 450 | 450
| 200 | 100 | 900 | 900 | 660
| 300 | -250 | 550 | 1350 | 630
|===



=== Decision-Making Under Uncertainty

In the processes of decision-making under uncertainty, the decision maker knows what are the possible states of nature, although they do not have any information about which of them will occur.
Not only is it unable to predict the real state that will occur, but it also cannot quantify this uncertainty in any way.
Particularly, this excludes knowledge of probabilistic information about the possibilities of occurrence of each state.

If it is possible to certainly forecast the consequences of each action alternative,
then we have the task to take decisions under uncertainty.

Some models or techniques used to handle these decisions are:

* Equilibrium point analysis
* Linear programming
* Production programming
* Inventory management

==== Decision-Making Based only on Probability

Used in a probabilistic concept of the mathematical expectation or expected value.

|===
| Market Demand | Probability
| stem:[E(1) = 5] | 0.1
| stem:[E(1) = 10] | 0.3
| stem:[E(1) = 15] | 0.4
| stem:[E(1) = 20] | 0.2
|===

.Formula
[stem]
++++
E(X) = \displaystyle\sum_{x = 1}^{n}{p * E(x)}
++++

==== Examples

===== 1

A heating and air conditioning sales and installation contractor must resolve by September 15 to purchase air conditioning units for resale and installation during the following summer.
Based on last summer's demand, current economic conditions, and competitive market factors, he estimates that there is a probability of 10% of selling only 5 units, a probability of 30% of selling 10 units, a probability of 40% of selling 15 units, and a probability of 20% of selling 20 units.
Air conditioning units can only be ordered in groups of 5 units, 
while their cost per unit is 1,000 USD and their selling price is 1,300 USD. 
Units not sold at the end of the season are returned to the manufacturer with a net credit of 800 USD, after the reduction of shipping costs.

===== 3

Based on a new technological approach, a manufacturer developed a 3D TV with a pipe of 36".
The owner of a small retail storage estimates the sale price to 1,800 USD, for the first three months, less than 6 TVs can be sold.
The profit margin for each sold TV is 200 USD.
If there are no sold TVs for those 3 months, the total lose for the retail will bee 300 USD.
Based only on this economic consequences,
get the best decisions, to acquire the number of TVs to offer in the store, from the point of view, if there are the next purchase possibilities probabilities, 20% for 2 units, 35% for 3, 40% for 4, and 5% for 5.

=== Decision-Making Under Conflict

== Minimax & Maximin Strategies

=== Maximin Strategy

Maximizes the minimum revenue that can be obtained, it looks for the best of the worst options.

=== Minimax Strategy

Minimizes to the edge the losses.
It looks for the worst of the best.

=== Saddle Point

Optimal values that each player can choose and where is that values the same for all players.
Identifies the best of the worst for each one.

|===
| | B1 | B2 | B3 | B4
| A1 | (4, -4) | (-4, 4) s| (-5, 5) | (6, -6)
| A2 | (-3, 3) | (-4, 4) | (-9, 9) | (-2, 2)
| A3 | (6, -6) | (7, -7) | (-8, 8) | (-9, 9)
| A4 | (7, -7) | (3, -3) | (-9, 9) | (5, -5)
|===

==== Example

dos companias a y b, venden dos marcas de un medicamento para la gripe.
la compania a se anuncia en radio, tv y periodicos.
la compania b se anuncia en todo lo de la a, mas folletos por correo.
dependiendo de la efectividad de cada compania publicitaria, una compania puede capturar una parte del mercado de la otra.
la siguiente matriz resume el porcentaje del mercado capturado o perdido por la compania a.

|===
| stem:[A_1] | 8 | -2 | 9 | -3 
| stem:[A_2] | 6 | 5 | 6 | 8
| stem:[A_3] | -2 | 4 | -9 | 5
|===
== Consecutive Games

los jugadores actuan sucesivamente, respondiendo a las decisiones del contrario.

ejemplo:
la introduccion de un nuevo producto al mercado por aprte de 2 empresas en dos presentaciones: grande y pequena.

== Decision Tree

=== Problems 

==== 1

el gerente de una empresa tiene dos disenos posibles para su nueva linea de cerebros electronicos, la primera opcion tiene un 0.8 de probabilidades de producir el 0.7 de cerebros electronicos buenos y un 0.2 de porbabilidades de producir el 0.5 de cerebros electronicos buenos, siendo el coste de este diseno de 450,000 EUR.
la seugnda opcion tiene una probaibilidad del 0.7 de producir el 0.7 de cerebros electornicos buenos y una proabbilidda del 0.3 de producir el 0.5 de cerebros de electronicos buenos, el coste de este diseno asciende a 600,000 EUR.
el coste de cada cerebro electronico es de 100 EUR, si es bueno se vende por 250 EUR, mientras que si es malo no tiene ningun valor.
conociendo que la prevision es de fabricar 50,000 cerebros electronicos, decida el diseno que debe elegir el gerente de la empresa.

==== 2

un establecimiento comercial esta analizando la posibilidad de realizar los pedidos de un determinaod producot con un mes de antelacion, con la finalidadd de evitar roturas de inventario.
si realiza el pedido con un mes de anticipacion, el coste por unidad de producto es de 50 EUR, por el contrario, si la demanda de dicho producto durante el mes excede el numero de unidades en almacen, debe ordenar las unidades necesarias a un coste de 100 EUR / unidad.
la tabal muestra la demanda mensual de dicho producto durante los 3 ultimos anos.

|===
| demanda (unidades) | frecuencia (meses)
| 10 | 20
| 20 | 12
| 30 | 8
|===

[plantuml]
....
@startuml
title
    compra
    |_ (1200, 10)
      |_
    |_ (1200, 20)
    |_ (1500, 30)
end title
@enduml
....

sugiera la politica de pedidos para la empresa asi como el coste de la misma.

