= Queueing Theory

== objetivos de la teoria de colas

* identificar el nivel optimo de capaciddad del sistema que minimiza el coste gloabl del mismo.
* evaluar el impacto que las posibles alternativas de modificacion de la capacidad del sistema tendrian en el coste total del mismo.
* establecer un balance equilibrado _optimo_ entre las consideraciones cuantitativas de costes y las cualitativas de servicio.

hay que prestar atencion al tiempo de permanencia en el sistema o en la cola: la paciencia de los clientes depende del tipo d eservicio especifico considerado y eso puede hacer que un cliente abandone el sistema.

== tipos de colas

una linea, un servidor::
un sistema de un servidor y una cola o puede describir una consulta de un medico.

una linea, varios servidores::
tipico de una peluqueria o una paaneria en donde los clientes toman un numero al entrar y se les sirve cuando les llega el turno.

varias lineas, varios servidores::
caracteristica de los bancos y tiendas de autoservicio

